name: playwright-java-soft-assertions 

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ '8', '11', '17' ]
        playwright: [ '1.35.1', '1.36.0']
    runs-on: ${{ matrix.os }}
    name: ${{matrix.os}} - Java ${{ matrix.java }} - Playwright ${{matrix.playwright}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: mvn clean test "-Dplaywright.version=${{matrix.playwright}}" --file pom.xml --no-transfer-progress
